---
abstract: 'Instantiate a Metabase backend for CPAN Testers'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Test::More: 0.62
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Testers-Metabase
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
provides:
  CPAN::Testers::Metabase:
    file: lib/CPAN/Testers/Metabase.pm
    version: 0.001
requires:
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CPAN-Testers-Metabase
  repository: http://github.com/dagolden/CPAN-Testers-Metabase/
version: 0.001
